modLoader = "javafml"
loaderVersion = "[${forge_loader_version},)"
issueTrackerURL = "${mod_repository}/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = "${mod_description}"
#logoFile = ""

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "[${forge_loader_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "supermartijn642configlib"
mandatory = true
versionRange = "[${config_library_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "uilib"
mandatory = true
versionRange = "[${ui_library_version},)"
ordering = "AFTER"
side = "CLIENT"

